name: Build and Test
on:
  push:
  pull_request:
    branches : [ develop ]

env:
  DOTNET_VERSION: '6.0.x'
  
jobs:
  build:
    runs-on: [ windows-latest ]
    
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
     
    - name: List all projects
      run: dotnet sln ./ClassLibrary1/ClassLibrary1.sln list

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore ./ClassLibrary1/ClassLibrary1.sln
    
    - name: Build
      run: dotnet build --configuration Release --no-restore ./ClassLibrary1/ClassLibrary1.sln
      
    - name: Test
      run: dotnet test --no-restore --collect "Code Coverage" --logger "console;verbosity=detailed" ./ClassLibrary1/ClassLibrary1.sln
    
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
          nuget-version: latest 
      
    - name: Pack ClassLibrary1
      run: dotnet pack --output . --configuration Release ./ClassLibrary1/ClassLibrary1.csproj
      
    - name: Push packages
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key '${{secrets.NUGET_API_KEY}}' --skip-duplicate
