name: Build and Test
on:
  push:
  pull_request:
    branches : [ develop ]

env:
  DOTNET_VERSION: '6.0.x'
  
jobs:
  build:
    runs-on: [ windows-latest ]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: List all projects
      run: dotnet sln Project.Remedy.sln list
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore ./ClassLibrary1/
    
    - name: Build
      run: dotnet build --configuration Release --no-restore ./ClassLibrary1/
      
    - name: Test
      run: dotnet test --no-restore --collect "Code Coverage" ./ClassLibrary1/
